name: Node CI

on:
  push:
  schedule:
    - cron: "* */6 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: node-version
        run: echo "::set-output name=version::$(cat .node-version)"
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.version }}
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --frozen-lockfile
      - run: node index.js
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          REPOSITORY_OWNER: ${{ secrets.REPOSITORY_OWNER }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
